version: "3.5"

services:
  db:
    image: postgres:13
    container_name: shows-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=shows-db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - shows-net
    restart: always

  api:
    build: .
    container_name: shows-api
    ports:
      - 8080:8080
    networks:
      - shows-net
    depends_on:
      - db
    restart: always

volumes:
  db-data:
    name: shows-api
networks:
  shows-net:
    name: shows-net